# Datasource (Dev Services / H2)
quarkus.datasource.db-kind=h2
quarkus.hibernate-orm.database.generation=validate
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=false

# Swagger
quarkus.smallrye-openapi.info-title=Weather API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Quarkus backend for the Android Weather App
%dev.quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

